### ISSUE TITLE
Internal server error, if publishing a non elemental page

### ISSUE THREAD

**Issue by conny-nyman** [jbennecker/silverstripe-elemental-site-search#1]
If you try to publish a normal page which do not have the ss-elemental extension attached, then you get this error: 
```
[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'getElementsForSearch' does not exist on 'Page'

jbennecker\ElementalSiteSearch\SiteTreeSearchExtension->collateSearchContent() 
SiteTreeSearchExtension.php:40
```

```
try {
    ...
    $content .= $this->getOwner()->getElementsForSearch();
    ....
}
```

The original code is wrapped in a `try` block, but it seems that it's SS itself that decides to return an error somewhere in the method call chain. 

One solution would be to check if the object returned by `getOwner` has the `elementalPageExtension` class, before calling `getElemenetsForSearch()`
```
// Get the elements content
$page = $this->getOwner();
if ($page::has_extension(ElementalPageExtension::class)) {
    $content .= $page->getElementsForSearch();
}
```

**Comment by jbennecker** [comment]
@conny-nyman can you make a pull request?

**Comment by conny-nyman** [comment]
> @conny-nyman can you make a pull request?

Sure, I will open a PR sometime this weekend!

**Comment by conny-nyman** [comment]
Open PR - https://github.com/jbennecker/silverstripe-elemental-site-search/pull/2

**Comment by jbennecker** [comment]
@conny-nyman thank you, i've merged your pull request
