### ISSUE TITLE
Allow extensions to mutate the search result list

### ISSUE THREAD

**Issue by conny-nyman** [jbennecker/silverstripe-elemental-site-search#3]
Currently it is possible to alter the search query, as `SearchForm->getResults` calls `$this->extend('updateSearchQuery', $sql);`. 

But there is no way to modify the returned paginated list variable from the `SearchForm->getResults` method. (Unless you override the class through the Injector)

Would it make sense to also call extensions right before returning the search result?
Something like this:
```
        $list = new PaginatedList($objects);
        $list->setPageStart($start);
        $list->setPageLength($pageLength);
        $list->setTotalItems($totalCount);
        $list->setLimitItems(false);

        // Call extensions which can mutate the search result before returning it.
        $this->extend('updateSearchResultList', $list, $keywords);

        return $list;
```

**Comment by jbennecker** [comment]
Sure why not. If you make a Pull Request, I'll merge it. I was wondering what kind of alteration you'd like to make?

**Comment by conny-nyman** [comment]
> I was wondering what kind of alteration you'd like to make?

I quickly realized after creating this issue that I don't really need the extension. I currently override the `getResults` method through the Injector, because I implemented my own search/filter logic for a site which had translated content with `silverstripe-fluent`, and I don't think its a good idea to do all this in an extension hook

I tried to delete this issue after creating it but it said only the owner of this repository can delete it, so I will close this issue. :)
