### ISSUE TITLE
Any other reason for PHP>=7.4.0 then type hints? (else can be 7.x?)

### ISSUE THREAD

**Issue by micschk** [jbennecker/silverstripe-elemental-site-search#4]
From the [PHP manual](https://www.php.net/manual/en/language.types.declarations.php): "Type declarations can be added to function arguments, return values, **and, as of PHP 7.4.0, class properties**". It's EOL'ed in a few days from now but we're still running PHP 7.3 on some servers, seems this module should be fine with that as well?

**Comment by jbennecker** [comment]
Hi @micschk, you're right. This module should run fine with php 7.3. i've edited the composer.json file but didn't actually test it. I'm closing this issue. Feel free to reopen if you run into any issues.
